### ISSUE TITLE
Scopes are empty for a Direct Samsung Health Integration

### ISSUE THREAD

**Issue by itsramiel** [tryterra/TerraAndroid#2]
Hi,

I am trying to init a direct samsung integration using the `0.2.10-beta` version which supports the direct samsung health integration.

I can init the connection and the data is being received by the webhook, however one issue is that the `scopes` is empty:
<img width="162" alt="image" src="https://github.com/user-attachments/assets/0b003c01-5786-43db-8aec-69f3a816cbd0">

A reproducable can be found [here](https://github.com/itsramiel/TerraDirectSamsung)

**Comment by terra-alex** [comment]
Hey Ramiel! scopes is mainly meant for debugging purposes. This will be investigated down the line when we aim to expand the functionality here
